name: Playwright Tests
on:
  push:
    branches: [main]
    paths-ignore:
      - 'openmetadata-docs/**'
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]
    paths-ignore:
      - 'openmetadata-docs/**'
jobs:
  test:
    timeout-minutes: 60
    build:
      runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Checkout
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generating Data Models
        run: |
          sudo make install_antlr_cli
          make install_dev generate

      - name: Start Server and Ingest Sample Data
        env:
          INGESTION_DEPENDENCY: 'all'
        run: ./docker/run_local_docker.sh
        timeout-minutes: 30

      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: openmetadata-ui/src/main/resources/ui/tests
        wait-on: 'http://localhost:8585'
        run: yarn playwright test
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
