name: 'Playwright Tests'
on:
  push:
    branches: [main]
    paths-ignore:
      - 'openmetadata-docs/**'
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]
    paths-ignore:
      - 'openmetadata-docs/**'

jobs:
  test:
    build:
      runs-on: ubuntu-latest
    steps:
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'
      - name: Checkout
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          ref: '${{ github.event.pull_request.head.sha }}'
      - name: 'Generating Data Models'
        run: |
          sudo make install_antlr_cli
          make install_dev generate
      - INGESTION_DEPENDENCY: all
        env: ~
        name: 'Start Server and Ingest Sample Data'
        run: ./docker/run_local_docker.sh
        timeout-minutes: 30
      - name: 'Install dependencies'
        run: yarn
      - name: 'Install Playwright Browsers'
        run: 'npx playwright install --with-deps'
      - name: 'Run Playwright tests'
        run: 'yarn playwright test'
        wait-on: 'http://localhost:8585'
        working-directory: openmetadata-ui/src/main/resources/ui
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
    timeout-minutes: 60
